import { useState, useMemo, useCallback, useEffect } from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartsTooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import {
  Search,
  TrendingUp,
  TrendingDown,
  RefreshCw,
  Unlink,
  Link2,
  MousePointerClick,
  Eye,
  Target,
  BarChart3,
  Loader2,
  CheckCircle,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  FileText,
  Zap,
  AlertTriangle,
  Award,
  ArrowUpRight,
  ArrowDownRight,
  Minus,
  Globe,
  Tag,
  Lightbulb,
  Activity,
  Filter,
  Sparkles,
  Copy,
  Check,
  Bot,
  BookOpen,
  History,
  Clock,
  Info,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { SEOConnectorHook, SEORow } from "@/hooks/useSEOConnector";
import TechnicalSEO from "@/components/seo/TechnicalSEO";
import CompetitiveIntel from "@/components/seo/CompetitiveIntel";
import ContentOnPage from "@/components/seo/ContentOnPage";
import BacklinkModule from "@/components/seo/BacklinkModule";
import ReportingGoals from "@/components/seo/ReportingGoals";

// ── Groq AI helper ────────────────────────────────────────────────────────────

async function callGroq(prompt: string, system: string, maxTokens = 2000): Promise<string> {
  const { data, error } = await supabase.functions.invoke('groq-proxy', {
    body: {
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: prompt },
      ],
      temperature: 0.4,
      max_tokens: maxTokens,
    },
  });
  if (error) throw new Error(`Function error: ${error.message}`);
  if (data?.error) throw new Error(`Groq error: ${data.error}`);
  if (!data?.response) throw new Error('Empty response from Groq');
  return data.response as string;
}

// ── AI Types ──────────────────────────────────────────────────────────────────

interface AIInsight {
  category: string;
  icon: string;
  title: string;
  body: string;
  actions: string[];
}

interface MetaGenResult {
  title: string;
  description: string;
}

interface ContentBrief {
  keyword: string;
  intent: string;
  suggestedTitle: string;
  headings: string[];
  wordCount: string;
  internalLinks: string[];
  outline: string;
}

interface SavedInsight {
  id: string;
  insight_type: string;
  query_context: string | null;
  engine: string | null;
  date_range: number | null;
  response: any;
  created_at: string;
}

// ── AI Disclaimer Component ────────────────────────────────────────────────────

function AIDisclaimer() {
  return (
    <div className="flex items-start gap-2 mt-3 px-3 py-2.5 rounded-lg bg-slate-50 border border-slate-200/80">
      <Info className="h-3.5 w-3.5 text-slate-400 flex-shrink-0 mt-0.5" />
      <p className="text-[11px] text-slate-500 leading-relaxed">
        <span className="font-semibold text-slate-600">AI-Generated Content</span> — This content was generated by AI as a starting point. We recommend reviewing and tailoring it to your brand voice, verifying all claims, and adjusting for your specific audience before publishing.
      </p>
    </div>
  );
}

// ── Types ─────────────────────────────────────────────────────────────────

interface EnrichedQuery {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
  isBrand: boolean;
  trend: "up" | "down" | "stable";
}

interface PageRow {
  page: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

// ── Helpers ────────────────────────────────────────────────────────────────

function fmt(n: number) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function fmtDate(s: string) {
  const d = new Date(s + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function fmtPos(p: number) { return p > 0 ? p.toFixed(1) : "—"; }
function fmtCTR(c: number) { return `${c.toFixed(1)}%`; }

function truncatePage(url: string, max = 52) {
  try {
    const u = new URL(url);
    const path = u.pathname + u.search;
    return path.length > max ? path.slice(0, max) + "…" : path;
  } catch {
    return url.length > max ? url.slice(0, max) + "…" : url;
  }
}

function detectBrand(query: string, brandName: string): boolean {
  if (!brandName) return false;
  const bn = brandName.toLowerCase().replace(/[^a-z0-9]/g, "");
  const qn = query.toLowerCase().replace(/[^a-z0-9]/g, "");
  return qn.includes(bn) || bn.includes(qn.slice(0, Math.max(3, bn.length - 1)));
}

function deltaIcon(delta: number | null) {
  if (delta === null || delta === 0) return <Minus className="h-3 w-3 text-gray-400" />;
  if (delta > 0) return <ArrowUpRight className="h-3 w-3 text-emerald-500" />;
  return <ArrowDownRight className="h-3 w-3 text-rose-500" />;
}

// ── Sub-components ─────────────────────────────────────────────────────────

function KpiCard({
  label, value, icon: Icon, color, sub, badge,
}: {
  label: string; value: string; icon: React.ElementType;
  color: string; sub?: string; badge?: React.ReactNode;
}) {
  return (
    <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5 flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">{label}</span>
        <div className={cn("p-2 rounded-xl", color)}>
          <Icon className="h-4 w-4 text-white" />
        </div>
      </div>
      <div>
        <div className="flex items-end gap-2">
          <p className="text-2xl font-bold text-gray-900">{value}</p>
          {badge}
        </div>
        {sub && <p className="text-xs text-gray-400 mt-0.5">{sub}</p>}
      </div>
    </div>
  );
}

function SectionHeader({ title, sub, action }: { title: string; sub?: string; action?: React.ReactNode }) {
  return (
    <div className="flex items-start justify-between mb-4">
      <div>
        <h3 className="text-sm font-bold text-gray-800">{title}</h3>
        {sub && <p className="text-xs text-gray-500 mt-0.5">{sub}</p>}
      </div>
      {action}
    </div>
  );
}

function CustomTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-white/95 backdrop-blur-sm border border-gray-200 rounded-xl shadow-2xl p-3.5 text-xs min-w-[170px]">
      <p className="font-bold text-gray-800 mb-2">{label}</p>
      {payload.map((e: any) => (
        <div key={e.name} className="flex items-center justify-between gap-4 py-0.5">
          <span className="flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full" style={{ backgroundColor: e.color }} />
            <span className="text-gray-600">{e.name}</span>
          </span>
          <span className="font-bold text-gray-900 tabular-nums">
            {e.name === "CTR" ? `${(e.value || 0).toFixed(2)}%`
              : e.name === "Avg Position" ? (e.value || 0).toFixed(1)
              : (e.value || 0).toLocaleString()}
          </span>
        </div>
      ))}
    </div>
  );
}

// ── Connect Panels ─────────────────────────────────────────────────────────

function GSCConnectPanel({ hook }: { hook: SEOConnectorHook }) {
  const { gscIntegration, gscSites, connectGSC, selectGSCSite, disconnectGSC, listGSCSites, syncing } = hook;

  if (!gscIntegration || gscIntegration.status === "disconnected") {
    return (
      <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-6 flex flex-col items-center text-center gap-4">
        <div className="p-4 bg-blue-50 rounded-2xl">
          <svg viewBox="0 0 48 48" className="h-10 w-10">
            <path fill="#EA4335" d="M24 9.5c3.5 0 6.6 1.3 9 3.4l6.7-6.7C35.9 2.6 30.3 0 24 0 14.6 0 6.6 5.5 2.6 13.5l7.8 6.1C12.4 13.2 17.7 9.5 24 9.5z"/>
            <path fill="#4285F4" d="M46.6 24.5c0-1.6-.1-3.1-.4-4.5H24v8.5h12.7c-.5 2.8-2.1 5.2-4.5 6.8l7 5.4c4.1-3.8 6.4-9.4 6.4-16.2z"/>
            <path fill="#FBBC05" d="M10.4 28.4A15 15 0 0 1 9.5 24c0-1.5.3-3 .8-4.4l-7.8-6.1A23.9 23.9 0 0 0 0 24c0 3.9.9 7.5 2.6 10.7l7.8-6.3z"/>
            <path fill="#34A853" d="M24 48c6.5 0 11.9-2.1 15.9-5.8l-7-5.4c-2.1 1.5-4.9 2.3-8.9 2.3-6.3 0-11.6-3.7-13.6-9.7l-7.8 6.3C6.6 42.5 14.6 48 24 48z"/>
          </svg>
        </div>
        <div>
          <h3 className="font-bold text-gray-900 text-base">Connect Google Search Console</h3>
          <p className="text-sm text-gray-500 mt-1 max-w-xs">Pull organic clicks, impressions, rankings and keyword data from Google.</p>
        </div>
        <Button onClick={connectGSC} className="bg-blue-600 hover:bg-blue-700 text-white gap-2">
          <Link2 className="h-4 w-4" /> Connect with Google
        </Button>
      </div>
    );
  }

  if (gscIntegration.status === "pending") {
    return (
      <div className="bg-white rounded-2xl border border-blue-200 shadow-sm p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 bg-blue-50 rounded-xl"><CheckCircle className="h-5 w-5 text-blue-600" /></div>
          <div>
            <p className="font-semibold text-gray-900">Google account connected</p>
            <p className="text-xs text-gray-500">{gscIntegration.connected_email}</p>
          </div>
        </div>
        <p className="text-sm text-gray-600 mb-3">Select the property to track:</p>
        {gscSites.length === 0 ? (
          <Button variant="outline" size="sm" onClick={listGSCSites} className="gap-2">
            <RefreshCw className="h-4 w-4" /> Load properties
          </Button>
        ) : (
          <div className="space-y-2 max-h-52 overflow-y-auto pr-1">
            {gscSites.map(s => (
              <button key={s.siteUrl} onClick={() => selectGSCSite(s.siteUrl)} disabled={syncing}
                className="w-full text-left px-3 py-2.5 rounded-xl border border-gray-200 hover:border-blue-300 hover:bg-blue-50 transition-all text-sm flex items-center justify-between group">
                <span className="text-gray-700 truncate">{s.siteUrl}</span>
                <ChevronRight className="h-4 w-4 text-gray-400 group-hover:text-blue-500 flex-shrink-0" />
              </button>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="flex items-center gap-3 bg-white rounded-2xl border border-green-200/80 shadow-sm px-4 py-3">
      <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-gray-900 truncate">{gscIntegration.site_url || "Site connected"}</p>
        <p className="text-xs text-gray-400">
          {gscIntegration.connected_email} · {gscIntegration.last_synced_at
            ? `Synced ${new Date(gscIntegration.last_synced_at).toLocaleDateString()}`
            : "Not yet synced"}
        </p>
      </div>
      <button onClick={disconnectGSC} className="p-2 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
        <Unlink className="h-4 w-4" />
      </button>
    </div>
  );
}

function BingConnectPanel({ hook }: { hook: SEOConnectorHook }) {
  const { bingIntegration, connectBing, disconnectBing, syncing } = hook;
  const [apiKey, setApiKey] = useState("");
  const [siteUrl, setSiteUrl] = useState("");

  if (!bingIntegration || bingIntegration.status === "disconnected") {
    return (
      <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-3 bg-orange-50 rounded-xl">
            <BarChart3 className="h-6 w-6 text-orange-500" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900">Connect Bing Webmaster</h3>
            <p className="text-sm text-gray-500">API key authentication</p>
          </div>
        </div>
        <div className="space-y-3">
          <div>
            <Label className="text-xs text-gray-600 mb-1.5 block">API Key</Label>
            <Input placeholder="Paste your Bing Webmaster API key" value={apiKey}
              onChange={e => setApiKey(e.target.value)} type="password" className="text-sm" />
          </div>
          <div>
            <Label className="text-xs text-gray-600 mb-1.5 block">Site URL</Label>
            <Input placeholder="https://example.com" value={siteUrl}
              onChange={e => setSiteUrl(e.target.value)} className="text-sm" />
          </div>
          <Button onClick={() => connectBing(apiKey, siteUrl)} disabled={!apiKey || !siteUrl || syncing}
            className="w-full bg-orange-500 hover:bg-orange-600 text-white gap-2">
            {syncing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Link2 className="h-4 w-4" />}
            Connect Bing Webmaster
          </Button>
          <p className="text-[11px] text-gray-400 text-center">
            Get your API key from Bing Webmaster Tools → Settings → API Access
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-3 bg-white rounded-2xl border border-green-200/80 shadow-sm px-4 py-3">
      <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-gray-900 truncate">{bingIntegration.site_url || "Bing connected"}</p>
        <p className="text-xs text-gray-400">
          {bingIntegration.last_synced_at
            ? `Synced ${new Date(bingIntegration.last_synced_at).toLocaleDateString()}`
            : "Not yet synced"}
        </p>
      </div>
      <button onClick={disconnectBing} className="p-2 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
        <Unlink className="h-4 w-4" />
      </button>
    </div>
  );
}

// ── Opportunity Badge ──────────────────────────────────────────────────────

function OpportunityBadge({ type }: { type: "quick-win" | "ctr" | "brand" | "nonbrand" }) {
  const cfg = {
    "quick-win": { label: "Quick Win", cls: "bg-emerald-100 text-emerald-700" },
    "ctr": { label: "Low CTR", cls: "bg-amber-100 text-amber-700" },
    "brand": { label: "Brand", cls: "bg-blue-100 text-blue-700" },
    "nonbrand": { label: "Non-Brand", cls: "bg-purple-100 text-purple-700" },
  }[type];
  return <span className={cn("text-[10px] font-semibold px-1.5 py-0.5 rounded", cfg.cls)}>{cfg.label}</span>;
}

// ── Main Component ─────────────────────────────────────────────────────────

interface SEOTabProps {
  seo: SEOConnectorHook;
  brandName?: string;
  clientId?: string;
  competitors?: string[];
}

export default function SEOTab({ seo, brandName = "", clientId, competitors = [] }: SEOTabProps) {
  const {
    gscIntegration, bingIntegration,
    gscData, bingData,
    gscMetrics, bingMetrics,
    gscTopQueries, gscTopPages,
    bingTopQueries, bingTopPages,
    gscDailyClicks, bingDailyClicks, gscCountries,
    loading, syncing,
    dateRange, setDateRange,
    syncGSC, syncBing,
  } = seo;

  const [activeEngine, setActiveEngine] = useState<"google" | "bing">("google");
  const [activeSection, setActiveSection] = useState<"overview" | "queries" | "pages" | "opportunities" | "countries" | "technical" | "competitive" | "content" | "backlinks" | "reports">("overview");
  const [querySearch, setQuerySearch] = useState("");
  const [pageSearch, setPageSearch] = useState("");
  const [queryFilter, setQueryFilter] = useState<"all" | "brand" | "nonbrand">("all");

  // ── AI State ────────────────────────────────────────────────────────────
  const [aiInsights, setAiInsights] = useState<AIInsight[] | null>(null);
  const [aiInsightsLoading, setAiInsightsLoading] = useState(false);
  const [metaGenResults, setMetaGenResults] = useState<Record<string, MetaGenResult>>({});
  const [metaGenLoading, setMetaGenLoading] = useState<Record<string, boolean>>({});
  const [expandedMetaQuery, setExpandedMetaQuery] = useState<string | null>(null);
  const [contentBrief, setContentBrief] = useState<ContentBrief | null>(null);
  const [contentBriefLoading, setContentBriefLoading] = useState(false);
  const [contentBriefQuery, setContentBriefQuery] = useState<string | null>(null);
  const [copiedText, setCopiedText] = useState<string | null>(null);
  const [insightHistory, setInsightHistory] = useState<SavedInsight[]>([]);
  const [showHistory, setShowHistory] = useState(false);

  const copyToClipboard = useCallback((text: string, label?: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedText(text);
      toast.success(label ? `${label} copied!` : "Copied to clipboard");
      setTimeout(() => setCopiedText(null), 2500);
    });
  }, []);

  // ── Load insight history from Supabase ──────────────────────────────────
  useEffect(() => {
    if (!clientId) return;
    (async () => {
      try {
        const { data } = await supabase
          .from('seo_ai_insights')
          .select('*')
          .eq('client_id', clientId)
          .order('created_at', { ascending: false })
          .limit(20);
        if (data) setInsightHistory(data as SavedInsight[]);
      } catch { /* silent */ }
    })();
  }, [clientId]);

  const saveInsightToSupabase = useCallback(async (
    type: string, response: any, queryContext?: string
  ) => {
    if (!clientId) return;
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const row = {
        client_id: clientId,
        user_id: user.id,
        insight_type: type,
        query_context: queryContext || null,
        engine: activeEngine,
        date_range: dateRange,
        response,
      };
      const { data } = await supabase
        .from('seo_ai_insights')
        .insert(row)
        .select()
        .single();
      if (data) {
        setInsightHistory(prev => [data as SavedInsight, ...prev].slice(0, 20));
      }
    } catch { /* non-critical */ }
  }, [clientId, activeEngine, dateRange]);

  const gscConnected = gscIntegration?.status === "connected";
  const bingConnected = bingIntegration?.status === "connected";
  const anyConnected = gscConnected || bingConnected;

  // ── Enriched query data ────────────────────────────────────────────────

  const enrichedQueries = useMemo((): EnrichedQuery[] => {
    const source = activeEngine === "google" ? gscTopQueries : bingTopQueries;
    // Compute per-query trend: compare clicks in first half vs second half of date range
    const rows = activeEngine === "google" ? gscData : bingData;
    const sorted = [...rows].filter(r => r.query && !r.page && !r.country).sort((a, b) => a.date.localeCompare(b.date));
    const mid = sorted.length > 0 ? sorted[Math.floor(sorted.length / 2)]?.date : null;
    const firstHalf: Record<string, number> = {};
    const secondHalf: Record<string, number> = {};
    for (const r of sorted) {
      if (!r.query) continue;
      if (mid && r.date < mid) firstHalf[r.query] = (firstHalf[r.query] || 0) + r.clicks;
      else secondHalf[r.query] = (secondHalf[r.query] || 0) + r.clicks;
    }
    return source.map(q => {
      const f = firstHalf[q.query] || 0;
      const s = secondHalf[q.query] || 0;
      const trend: "up" | "down" | "stable" = f === 0 ? "stable" : s > f * 1.1 ? "up" : s < f * 0.9 ? "down" : "stable";
      return { ...q, isBrand: detectBrand(q.query, brandName), trend };
    });
  }, [activeEngine, gscTopQueries, bingTopQueries, gscData, bingData, brandName]);

  // ── Brand vs Non-brand split ───────────────────────────────────────────

  const brandSplit = useMemo(() => {
    const brand = enrichedQueries.filter(q => q.isBrand);
    const nonBrand = enrichedQueries.filter(q => !q.isBrand);
    const brandClicks = brand.reduce((s, q) => s + q.clicks, 0);
    const nonBrandClicks = nonBrand.reduce((s, q) => s + q.clicks, 0);
    const total = brandClicks + nonBrandClicks || 1;
    return {
      brandClicks, nonBrandClicks,
      brandPct: Math.round((brandClicks / total) * 100),
      nonBrandPct: Math.round((nonBrandClicks / total) * 100),
      brandCount: brand.length,
      nonBrandCount: nonBrand.length,
    };
  }, [enrichedQueries]);

  // ── Quick wins: position 4–20, impressions > threshold ─────────────────

  const quickWins = useMemo(() => {
    const avgImpressions = enrichedQueries.reduce((s, q) => s + q.impressions, 0) / (enrichedQueries.length || 1);
    const threshold = Math.max(50, avgImpressions * 0.1);
    return enrichedQueries
      .filter(q => q.position >= 4 && q.position <= 20 && q.impressions >= threshold)
      .sort((a, b) => b.impressions - a.impressions)
      .slice(0, 15);
  }, [enrichedQueries]);

  // ── CTR opportunities: impressions > threshold, CTR below average ──────

  const ctrOpportunities = useMemo(() => {
    const avgCTR = enrichedQueries.reduce((s, q) => s + q.ctr, 0) / (enrichedQueries.length || 1);
    const avgImpressions = enrichedQueries.reduce((s, q) => s + q.impressions, 0) / (enrichedQueries.length || 1);
    const threshold = Math.max(100, avgImpressions * 0.15);
    return enrichedQueries
      .filter(q => q.impressions >= threshold && q.ctr < avgCTR * 0.7)
      .sort((a, b) => b.impressions - a.impressions)
      .slice(0, 15);
  }, [enrichedQueries]);

  // ── Declining queries ──────────────────────────────────────────────────

  const decliningQueries = useMemo(() =>
    enrichedQueries.filter(q => q.trend === "down").sort((a, b) => b.clicks - a.clicks).slice(0, 10),
    [enrichedQueries]);

  // ── SEO Health Score ───────────────────────────────────────────────────

  const seoScore = useMemo(() => {
    if (enrichedQueries.length === 0) return null;
    const metrics = activeEngine === "google" ? gscMetrics : bingMetrics;
    let score = 50;
    // Position score: avg position < 5 = full marks
    if (metrics.avgPosition > 0) {
      const posScore = Math.max(0, Math.min(25, ((20 - metrics.avgPosition) / 15) * 25));
      score = 25 + posScore;
    }
    // CTR score
    const ctrScore = Math.min(25, (metrics.avgCTR / 5) * 25);
    score += ctrScore;
    // Quick wins potential (more wins = lower score)
    const winsScore = Math.max(0, 25 - quickWins.length * 1.5);
    score += winsScore;
    return Math.round(Math.min(100, Math.max(0, score)));
  }, [enrichedQueries, activeEngine, gscMetrics, bingMetrics, quickWins]);

  const seoScoreColor = seoScore === null ? "text-gray-400"
    : seoScore >= 75 ? "text-emerald-600"
    : seoScore >= 50 ? "text-amber-600"
    : "text-rose-600";

  const seoScoreBg = seoScore === null ? "bg-gray-100"
    : seoScore >= 75 ? "bg-emerald-50"
    : seoScore >= 50 ? "bg-amber-50"
    : "bg-rose-50";

  // ── Filtered queries ───────────────────────────────────────────────────

  const filteredQueries = useMemo(() => enrichedQueries
    .filter(q => queryFilter === "all" || (queryFilter === "brand" ? q.isBrand : !q.isBrand))
    .filter(q => !querySearch || q.query.toLowerCase().includes(querySearch.toLowerCase())),
    [enrichedQueries, queryFilter, querySearch]);

  const filteredPages = useMemo(() => (activeEngine === "google" ? gscTopPages : bingTopPages)
    .filter(p => !pageSearch || p.page.toLowerCase().includes(pageSearch.toLowerCase())),
    [activeEngine, gscTopPages, bingTopPages, pageSearch]);

  const metrics = activeEngine === "google" ? gscMetrics : bingMetrics;

  // ── AI Generation Functions ─────────────────────────────────────────────

  const generateAIInsights = useCallback(async () => {
    setAiInsightsLoading(true);
    try {
      const topQueriesStr = enrichedQueries.length > 0 
        ? enrichedQueries.slice(0, 10).map(q => `"${q.query}" (pos: ${q.position.toFixed(1)}, clicks: ${q.clicks}, impr: ${q.impressions}, CTR: ${q.ctr.toFixed(1)}%, trend: ${q.trend})`).join("\n")
        : "No query data available yet.";
      
      const quickWinsStr = quickWins.length > 0 
        ? quickWins.slice(0, 5).map(q => `"${q.query}" (pos: ${q.position.toFixed(1)}, ${q.impressions} impr)`).join(", ")
        : "None identified currently.";
      
      const ctrOppsStr = ctrOpportunities.length > 0
        ? ctrOpportunities.slice(0, 5).map(q => `"${q.query}" (${q.impressions} impr, ${q.ctr.toFixed(1)}% CTR)`).join(", ")
        : "None identified currently.";
      
      const decliningStr = decliningQueries.length > 0 
        ? decliningQueries.slice(0, 5).map(q => `"${q.query}" (${q.clicks} clicks)`).join(", ")
        : "Looking good, no significant declines.";

      const prompt = `Analyze this SEO data and give actionable recommendations.

METRICS SUMMARY:
- Total Clicks: ${metrics.totalClicks.toLocaleString()}
- Total Impressions: ${metrics.totalImpressions.toLocaleString()}
- Avg CTR: ${metrics.avgCTR.toFixed(2)}%
- Avg Position: ${metrics.avgPosition.toFixed(1)}
- Brand Name: ${brandName || "unknown"}
- Brand vs Non-Brand: ${brandSplit.brandPct}% brand / ${brandSplit.nonBrandPct}% non-brand
- Date Range: Last ${dateRange} days

TOP 10 QUERIES:
${topQueriesStr}

QUICK WIN KEYWORDS (position 4-20, high impressions): ${quickWinsStr || "None"}
CTR OPPORTUNITIES (high impressions, low CTR): ${ctrOppsStr || "None"}
DECLINING QUERIES: ${decliningStr || "None"}

Return a JSON array of exactly 4 insight objects:
[
  {
    "category": "quick_wins",
    "icon": "⚡",
    "title": "one-line recommendation title",
    "body": "2-3 sentence actionable advice with specific keywords mentioned",
    "actions": ["specific action 1", "specific action 2"]
  }
]

Categories MUST be: quick_wins, ctr_optimization, declining_recovery, growth_opportunity
Be specific — reference actual queries from the data. No generic advice.`;

      const response = await callGroq(prompt,
        "You are an expert SEO strategist. Analyze real search data and provide specific, actionable recommendations. Return ONLY valid JSON — no markdown fences, no explanation.",
        2000
      );
      
      // Parse JSON response
      const cleaned = response.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      const parsed = JSON.parse(cleaned) as AIInsight[];
      setAiInsights(parsed);
      saveInsightToSupabase('strategist', parsed);
      toast.success("AI insights generated!");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error("[SEO AI] Error:", msg);
      toast.error(`AI generation failed: ${msg}`);
    } finally {
      setAiInsightsLoading(false);
    }
  }, [enrichedQueries, quickWins, ctrOpportunities, decliningQueries, metrics, brandName, brandSplit, dateRange, saveInsightToSupabase]);

  const generateMetaDescription = useCallback(async (query: string, position: number, ctr: number, impressions: number) => {
    setMetaGenLoading(prev => ({ ...prev, [query]: true }));
    setExpandedMetaQuery(query);
    try {
      const prompt = `Generate an optimized meta title and meta description for this search query:

Query: "${query}"
Current Position: ${position.toFixed(1)}
Current CTR: ${ctr.toFixed(1)}%
Impressions: ${impressions.toLocaleString()}
Brand: ${brandName || "the website"}

Return ONLY a JSON object:
{
  "title": "SEO-optimized title tag (50-60 chars max, include the keyword naturally)",
  "description": "Compelling meta description (150-160 chars max, include a clear CTA, use the keyword naturally, convey value)"
}`;

      const response = await callGroq(prompt,
        "You are an SEO copywriting expert. Create click-worthy, keyword-optimized meta tags that improve CTR. Return ONLY valid JSON.",
        400
      );
      
      const cleaned = response.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      const parsed = JSON.parse(cleaned) as MetaGenResult;
      setMetaGenResults(prev => ({ ...prev, [query]: parsed }));
      saveInsightToSupabase('meta_description', parsed, query);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`Meta generation failed: ${msg}`);
    } finally {
      setMetaGenLoading(prev => ({ ...prev, [query]: false }));
    }
  }, [brandName, saveInsightToSupabase]);

  const generateContentBriefForQuery = useCallback(async (query: string, position: number, impressions: number) => {
    setContentBriefLoading(true);
    setContentBriefQuery(query);
    try {
      const prompt = `Create a comprehensive content brief for this keyword:

Target Keyword: "${query}"
Current Position: ${position.toFixed(1)}
Monthly Impressions: ${impressions.toLocaleString()}
Brand: ${brandName || "the website"}

Return ONLY a JSON object:
{
  "keyword": "${query}",
  "intent": "informational|transactional|navigational|commercial",
  "suggestedTitle": "H1 title for the content",
  "headings": ["H2 heading 1", "H2 heading 2", "H2 heading 3", "H2 heading 4"],
  "wordCount": "recommended word count range (e.g. 1500-2000)",
  "internalLinks": ["suggest 2-3 related page topics to link to"],
  "outline": "A 3-4 sentence summary of what the content should cover, structured approach, and how to differentiate from competitors"
}`;

      const response = await callGroq(prompt,
        "You are a content strategy expert. Create detailed, actionable content briefs for SEO. Return ONLY valid JSON.",
        800
      );
      
      const cleaned = response.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      const parsed = JSON.parse(cleaned) as ContentBrief;
      setContentBrief(parsed);
      saveInsightToSupabase('content_brief', parsed, query);
      toast.success("Content brief generated!");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`Brief generation failed: ${msg}`);
    } finally {
      setContentBriefLoading(false);
    }
  }, [brandName, saveInsightToSupabase]);

  // ── Pie data for brand split ───────────────────────────────────────────

  const brandPieData = [
    { name: "Brand", value: brandSplit.brandClicks, color: "#3b82f6" },
    { name: "Non-Brand", value: brandSplit.nonBrandClicks, color: "#8b5cf6" },
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-gray-300" />
      </div>
    );
  }

  return (
    <div className="space-y-5">

      {/* ── Connection row ──────────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Google Search Console</p>
          <GSCConnectPanel hook={seo} />
        </div>
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Bing Webmaster Tools</p>
          <BingConnectPanel hook={seo} />
        </div>
      </div>

      {!anyConnected && (
        <div className="bg-blue-50 border border-blue-200/60 rounded-2xl p-8 text-center">
          <Search className="h-10 w-10 text-blue-300 mx-auto mb-3" />
          <p className="text-sm font-semibold text-blue-900">Connect a data source to unlock SEO insights</p>
          <p className="text-xs text-blue-600 mt-1">Connect Google Search Console or Bing Webmaster Tools above.</p>
        </div>
      )}

      {anyConnected && (
        <>
          {/* ── Controls bar ─────────────────────────────────────────────────── */}
          <div className="flex items-center gap-3 flex-wrap">
            {/* Engine toggle */}
            <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
              {gscConnected && (
                <button onClick={() => setActiveEngine("google")}
                  className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                    activeEngine === "google" ? "bg-white shadow-sm text-blue-700" : "text-gray-500 hover:text-gray-700")}>
                  <svg viewBox="0 0 20 20" className="h-3.5 w-3.5">
                    <path fill="#4285F4" d="M10 8.2V11h5.1c-.2 1.3-.8 2.4-1.7 3.1l2.7 2.1c1.6-1.5 2.5-3.7 2.5-6.3 0-.6-.1-1.2-.2-1.7H10z"/>
                    <path fill="#34A853" d="M4.4 12.1A6 6 0 0 0 4 10c0-.7.1-1.4.4-2.1L1.7 5.8A10 10 0 0 0 0 10c0 1.6.4 3.1 1.1 4.4l3.3-2.3z"/>
                    <path fill="#FBBC05" d="M10 4c1.7 0 3.2.6 4.4 1.6L17 2.9C15.2 1.2 12.7 0 10 0 6.1 0 2.7 2.2 1.1 5.4l3.3 2.5C5.2 5.5 7.4 4 10 4z"/>
                    <path fill="#EA4335" d="M10 20c2.7 0 4.9-.9 6.5-2.4l-3-2.3c-.8.6-2 1-3.5 1-2.6 0-4.8-1.5-5.6-4l-3.3 2.3C3.3 17.8 6.4 20 10 20z"/>
                  </svg>
                  Google
                </button>
              )}
              {bingConnected && (
                <button onClick={() => setActiveEngine("bing")}
                  className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                    activeEngine === "bing" ? "bg-white shadow-sm text-orange-600" : "text-gray-500 hover:text-gray-700")}>
                  <BarChart3 className="h-3.5 w-3.5 text-orange-500" /> Bing
                </button>
              )}
            </div>

            {/* Date range */}
            <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
              {([28, 90] as const).map(d => (
                <button key={d} onClick={() => setDateRange(d)}
                  className={cn("px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                    dateRange === d ? "bg-white shadow-sm text-gray-800" : "text-gray-500 hover:text-gray-700")}>
                  {d}d
                </button>
              ))}
            </div>

            {/* Sync */}
            <div className="flex gap-2 ml-auto">
              {gscConnected && activeEngine === "google" && (
                <Button variant="outline" size="sm" onClick={syncGSC} disabled={syncing} className="gap-2 text-xs h-8">
                  {syncing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
                  Sync GSC
                </Button>
              )}
              {bingConnected && activeEngine === "bing" && (
                <Button variant="outline" size="sm" onClick={syncBing} disabled={syncing} className="gap-2 text-xs h-8">
                  {syncing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
                  Sync Bing
                </Button>
              )}
            </div>
          </div>

          {/* ── Section nav ───────────────────────────────────────────────────── */}
          <div className="flex gap-1 bg-gray-50 rounded-xl p-1 w-fit flex-wrap">
            {[
              { id: "overview", label: "Overview", icon: Activity },
              { id: "opportunities", label: "Opportunities", icon: Zap, badge: quickWins.length + ctrOpportunities.length },
              { id: "queries", label: "Queries", icon: Search },
              { id: "pages", label: "Pages", icon: FileText },
              { id: "countries", label: "Countries", icon: Globe },
              { id: "technical", label: "Technical", icon: Activity },
              { id: "competitive", label: "Competitive", icon: Target },
              { id: "content", label: "Content", icon: BookOpen },
              { id: "backlinks", label: "Backlinks", icon: Link2 },
              { id: "reports", label: "Reports", icon: FileText },
            ].map(s => (
              <button key={s.id} onClick={() => setActiveSection(s.id as any)}
                className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all",
                  activeSection === s.id ? "bg-white shadow-sm text-gray-800" : "text-gray-500 hover:text-gray-700")}>
                <s.icon className="h-3.5 w-3.5" />
                {s.label}
                {s.badge && s.badge > 0 && (
                  <span className="bg-amber-100 text-amber-700 text-[10px] font-bold px-1.5 py-0.5 rounded-full">{s.badge}</span>
                )}
              </button>
            ))}
          </div>

          {/* ─────────────────── OVERVIEW ────────────────────────────────────── */}
          {activeSection === "overview" && (
            <div className="space-y-5">
              {/* KPI + Score row */}
              <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
                {/* SEO Score */}
                <div className={cn("rounded-2xl border border-gray-200/80 shadow-sm p-5 flex flex-col gap-2 col-span-1", seoScoreBg)}>
                  <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">SEO Score</span>
                  <p className={cn("text-3xl font-bold", seoScoreColor)}>
                    {seoScore !== null ? seoScore : "—"}
                  </p>
                  <p className="text-xs text-gray-500">
                    {seoScore === null ? "No data" : seoScore >= 75 ? "Good" : seoScore >= 50 ? "Needs work" : "Poor"}
                  </p>
                </div>

                <KpiCard label="Total Clicks" value={fmt(metrics.totalClicks)} icon={MousePointerClick}
                  color="bg-blue-500" sub={`Last ${dateRange} days`} />
                <KpiCard label="Impressions" value={fmt(metrics.totalImpressions)} icon={Eye}
                  color="bg-indigo-500" sub={`Last ${dateRange} days`} />
                <KpiCard label="Avg CTR" value={fmtCTR(metrics.avgCTR)} icon={Target}
                  color="bg-emerald-500" sub="Click-through rate" />
                <KpiCard label="Avg Position" value={metrics.avgPosition > 0 ? fmtPos(metrics.avgPosition) : "—"}
                  icon={TrendingUp} color="bg-amber-500" sub="Search ranking" />
              </div>

              {/* Traffic chart */}
              {(activeEngine === "google" ? gscDailyClicks : bingDailyClicks).length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                  <SectionHeader title={`Organic Clicks & Impressions — Last ${dateRange} Days`} />
                  <ResponsiveContainer width="100%" height={220}>
                    <AreaChart data={activeEngine === "google" ? gscDailyClicks : bingDailyClicks} margin={{ top: 4, right: 8, bottom: 0, left: 0 }}>
                      <defs>
                        <linearGradient id="clicksGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor={activeEngine === "google" ? "#3b82f6" : "#f97316"} stopOpacity={0.18} />
                          <stop offset="95%" stopColor={activeEngine === "google" ? "#3b82f6" : "#f97316"} stopOpacity={0} />
                        </linearGradient>
                        <linearGradient id="impGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor={activeEngine === "google" ? "#818cf8" : "#fb923c"} stopOpacity={0.13} />
                          <stop offset="95%" stopColor={activeEngine === "google" ? "#818cf8" : "#fb923c"} stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" vertical={false} />
                      <XAxis dataKey="date" tickFormatter={fmtDate} tick={{ fontSize: 11, fill: "#9ca3af" }}
                        axisLine={false} tickLine={false} interval="preserveStartEnd" />
                      <YAxis tick={{ fontSize: 11, fill: "#9ca3af" }} axisLine={false} tickLine={false} width={40} />
                      <RechartsTooltip content={<CustomTooltip />} />
                      <Area type="monotone" dataKey="clicks" name="Clicks" stroke={activeEngine === "google" ? "#3b82f6" : "#f97316"} strokeWidth={2}
                        fill="url(#clicksGrad)" dot={false} />
                      <Area type="monotone" dataKey="impressions" name="Impressions" stroke={activeEngine === "google" ? "#818cf8" : "#fb923c"} strokeWidth={1.5}
                        fill="url(#impGrad)" dot={false} />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              )}

              {/* Brand vs Non-Brand + Declining row */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {/* Brand split */}
                {enrichedQueries.length > 0 && (
                  <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                    <SectionHeader title="Brand vs Non-Brand Traffic"
                      sub="Branded queries include your brand name" />
                    <div className="flex items-center gap-6">
                      <div className="w-28 h-28 flex-shrink-0">
                        <ResponsiveContainer width="100%" height="100%">
                          <PieChart>
                            <Pie data={brandPieData} dataKey="value" cx="50%" cy="50%"
                              innerRadius={28} outerRadius={48} paddingAngle={3}>
                              {brandPieData.map((entry, i) => (
                                <Cell key={i} fill={entry.color} />
                              ))}
                            </Pie>
                          </PieChart>
                        </ResponsiveContainer>
                      </div>
                      <div className="flex-1 space-y-3">
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <span className="flex items-center gap-1.5 text-xs text-gray-600">
                              <span className="w-2.5 h-2.5 rounded-full bg-blue-500" />
                              Brand
                            </span>
                            <span className="text-xs font-bold text-gray-900">{brandSplit.brandPct}%</span>
                          </div>
                          <div className="h-1.5 bg-gray-100 rounded-full">
                            <div className="h-full bg-blue-500 rounded-full" style={{ width: `${brandSplit.brandPct}%` }} />
                          </div>
                          <p className="text-[11px] text-gray-400 mt-0.5">{fmt(brandSplit.brandClicks)} clicks · {brandSplit.brandCount} queries</p>
                        </div>
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <span className="flex items-center gap-1.5 text-xs text-gray-600">
                              <span className="w-2.5 h-2.5 rounded-full bg-purple-500" />
                              Non-Brand
                            </span>
                            <span className="text-xs font-bold text-gray-900">{brandSplit.nonBrandPct}%</span>
                          </div>
                          <div className="h-1.5 bg-gray-100 rounded-full">
                            <div className="h-full bg-purple-500 rounded-full" style={{ width: `${brandSplit.nonBrandPct}%` }} />
                          </div>
                          <p className="text-[11px] text-gray-400 mt-0.5">{fmt(brandSplit.nonBrandClicks)} clicks · {brandSplit.nonBrandCount} queries</p>
                        </div>
                      </div>
                    </div>
                    {brandSplit.brandPct > 70 && (
                      <div className="mt-3 flex items-start gap-2 bg-amber-50 border border-amber-200/60 rounded-xl p-3">
                        <AlertTriangle className="h-4 w-4 text-amber-500 flex-shrink-0 mt-0.5" />
                        <p className="text-xs text-amber-800">High brand traffic dependency. Focus on non-brand keywords to grow organic reach.</p>
                      </div>
                    )}
                  </div>
                )}

                {/* Declining queries */}
                <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                  <SectionHeader title="Trending Queries"
                    sub="Comparing first half vs second half of selected period" />
                  {decliningQueries.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-6 text-center">
                      <CheckCircle className="h-8 w-8 text-emerald-400 mb-2" />
                      <p className="text-sm text-gray-500">No declining queries — looking good!</p>
                    </div>
                  ) : (
                    <div className="space-y-1.5">
                      <p className="text-[11px] font-semibold text-rose-500 uppercase tracking-wider mb-2">Declining ({decliningQueries.length})</p>
                      {decliningQueries.slice(0, 8).map(q => (
                        <div key={q.query} className="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50">
                          <TrendingDown className="h-3.5 w-3.5 text-rose-400 flex-shrink-0" />
                          <span className="text-xs text-gray-700 flex-1 truncate">{q.query}</span>
                          <span className="text-xs font-semibold text-gray-900 tabular-nums">{fmt(q.clicks)} clicks</span>
                          {q.isBrand && <OpportunityBadge type="brand" />}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Top queries + pages mini-tables */}
              <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
                <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                  <SectionHeader title="Top Queries" action={
                    <button onClick={() => setActiveSection("queries")} className="text-xs text-blue-500 hover:underline">View all</button>
                  } />
                  <QueryTable rows={enrichedQueries.slice(0, 8)} showTrend />
                </div>
                <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                  <SectionHeader title="Top Pages" action={
                    <button onClick={() => setActiveSection("pages")} className="text-xs text-blue-500 hover:underline">View all</button>
                  } />
                  <PageTable rows={(activeEngine === "google" ? gscTopPages : bingTopPages).slice(0, 8)} />
                </div>
              </div>
            </div>
          )}

          {/* ─────────────────── OPPORTUNITIES ───────────────────────────────── */}
          {activeSection === "opportunities" && (
            <div className="space-y-4">
              {/* Summary pills */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="bg-emerald-50 border border-emerald-200/60 rounded-2xl p-4 flex items-center gap-3">
                  <div className="p-2.5 bg-emerald-500 rounded-xl"><Zap className="h-5 w-5 text-white" /></div>
                  <div>
                    <p className="text-xl font-bold text-emerald-700">{quickWins.length}</p>
                    <p className="text-xs text-emerald-600">Quick Win Keywords</p>
                    <p className="text-[11px] text-emerald-500">Position 4–20, high impressions</p>
                  </div>
                </div>
                <div className="bg-amber-50 border border-amber-200/60 rounded-2xl p-4 flex items-center gap-3">
                  <div className="p-2.5 bg-amber-500 rounded-xl"><Target className="h-5 w-5 text-white" /></div>
                  <div>
                    <p className="text-xl font-bold text-amber-700">{ctrOpportunities.length}</p>
                    <p className="text-xs text-amber-600">CTR Opportunities</p>
                    <p className="text-[11px] text-amber-500">High impressions, low CTR</p>
                  </div>
                </div>
                <div className="bg-rose-50 border border-rose-200/60 rounded-2xl p-4 flex items-center gap-3">
                  <div className="p-2.5 bg-rose-500 rounded-xl"><TrendingDown className="h-5 w-5 text-white" /></div>
                  <div>
                    <p className="text-xl font-bold text-rose-700">{decliningQueries.length}</p>
                    <p className="text-xs text-rose-600">Declining Queries</p>
                    <p className="text-[11px] text-rose-500">Losing traffic vs prior period</p>
                  </div>
                </div>
              </div>

              {/* Quick wins */}
              <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                <SectionHeader
                  title="Quick Win Keywords"
                  sub="Ranking 4–20 with good impressions — a small push can move these to top 3"
                />
                {quickWins.length === 0 ? (
                  <div className="text-center py-6 text-gray-400 text-sm">No quick wins identified</div>
                ) : (
                  <>
                    <div className="grid grid-cols-[1fr_70px_80px_60px_60px_85px] gap-2 px-2 pb-2 border-b border-gray-100">
                      {["Query","Position","Impr.","Clicks","CTR",""].map(h => (
                        <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
                      ))}
                    </div>
                    <div className="space-y-0.5 mt-1 max-h-[400px] overflow-y-auto">
                      {quickWins.map(q => (
                        <div key={q.query}>
                          <div className="grid grid-cols-[1fr_70px_80px_60px_60px_85px] gap-2 px-2 py-2 rounded-lg hover:bg-emerald-50/50 group">
                            <span className="text-xs text-gray-700 truncate flex items-center gap-1.5">
                              {q.query}
                              {q.isBrand && <OpportunityBadge type="brand" />}
                            </span>
                            <span className="text-xs font-bold text-emerald-600 tabular-nums text-right">{fmtPos(q.position)}</span>
                            <span className="text-xs text-gray-600 tabular-nums text-right">{fmt(q.impressions)}</span>
                            <span className="text-xs text-gray-600 tabular-nums text-right">{fmt(q.clicks)}</span>
                            <span className="text-xs text-gray-600 tabular-nums text-right">{fmtCTR(q.ctr)}</span>
                            <button
                              onClick={() => generateMetaDescription(q.query, q.position, q.ctr, q.impressions)}
                              disabled={metaGenLoading[q.query]}
                              className="px-2 py-1 flex items-center justify-center gap-1 text-[10px] font-semibold bg-emerald-50 text-emerald-600 rounded border border-emerald-200 hover:bg-emerald-100 transition-colors"
                              title="Generate optimized meta tags with AI"
                            >
                              {metaGenLoading[q.query] ? <Loader2 className="h-3 w-3 animate-spin text-emerald-500" /> : <Sparkles className="h-3 w-3 text-emerald-500" />}
                              Auto-Meta
                            </button>
                          </div>
                          {expandedMetaQuery === q.query && metaGenResults[q.query] && (
                            <div className="mx-2 mb-2 p-3 bg-gradient-to-r from-emerald-50 to-blue-50 border border-emerald-200/60 rounded-xl space-y-2 animate-in slide-in-from-top-1">
                              <div className="flex items-center gap-2 mb-1">
                                <Bot className="h-3.5 w-3.5 text-emerald-600" />
                                <span className="text-[10px] font-bold text-emerald-700 uppercase tracking-wider">AI-Generated Meta Tags</span>
                                <button onClick={() => setExpandedMetaQuery(null)} className="ml-auto p-0.5 rounded hover:bg-white/50">
                                  <ChevronUp className="h-3 w-3 text-gray-400" />
                                </button>
                              </div>
                              <div className="space-y-1.5">
                                <div className="flex items-start gap-2">
                                  <span className="text-[10px] font-semibold text-gray-500 uppercase w-12 flex-shrink-0 mt-0.5">Title</span>
                                  <p className="text-xs text-gray-800 flex-1">{metaGenResults[q.query].title}</p>
                                  <button onClick={() => copyToClipboard(metaGenResults[q.query].title, "Title")} className="p-1 rounded hover:bg-white/60 flex-shrink-0">
                                    {copiedText === metaGenResults[q.query].title ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-gray-400" />}
                                  </button>
                                </div>
                                <div className="flex items-start gap-2">
                                  <span className="text-[10px] font-semibold text-gray-500 uppercase w-12 flex-shrink-0 mt-0.5">Desc</span>
                                  <p className="text-xs text-gray-800 flex-1">{metaGenResults[q.query].description}</p>
                                  <button onClick={() => copyToClipboard(metaGenResults[q.query].description, "Description")} className="p-1 rounded hover:bg-white/60 flex-shrink-0">
                                    {copiedText === metaGenResults[q.query].description ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-gray-400" />}
                                  </button>
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </div>

              {/* CTR opportunities */}
              <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
                <SectionHeader
                  title="CTR Opportunities"
                  sub="High visibility but low click-through — improving title tags and meta descriptions can help"
                />
                {ctrOpportunities.length === 0 ? (
                  <div className="text-center py-6 text-gray-400 text-sm">No CTR opportunities identified</div>
                ) : (
                  <>
                    <div className="grid grid-cols-[1fr_80px_80px_60px_85px] gap-2 px-2 pb-2 border-b border-gray-100">
                      {["Query","Impressions","CTR","Pos.",""].map(h => (
                        <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
                      ))}
                    </div>
                    <div className="space-y-0.5 mt-1 max-h-[400px] overflow-y-auto">
                      {ctrOpportunities.map(q => (
                        <div key={q.query}>
                          <div className="grid grid-cols-[1fr_80px_80px_60px_85px] gap-2 px-2 py-2 rounded-lg hover:bg-amber-50/50 group">
                            <span className="text-xs text-gray-700 truncate flex items-center gap-1.5">
                              {q.query}
                              <OpportunityBadge type="ctr" />
                            </span>
                            <span className="text-xs text-gray-600 tabular-nums text-right">{fmt(q.impressions)}</span>
                            <span className="text-xs font-bold text-amber-600 tabular-nums text-right">{fmtCTR(q.ctr)}</span>
                            <span className="text-xs text-gray-600 tabular-nums text-right">{fmtPos(q.position)}</span>
                            <button
                              onClick={() => generateMetaDescription(q.query, q.position, q.ctr, q.impressions)}
                              disabled={metaGenLoading[q.query]}
                              className="px-2 py-1 flex items-center justify-center gap-1 text-[10px] font-semibold bg-amber-50 text-amber-600 border border-amber-200 rounded hover:bg-amber-100 transition-colors"
                              title="Generate optimized meta tags with AI"
                            >
                              {metaGenLoading[q.query] ? <Loader2 className="h-3 w-3 animate-spin text-amber-500" /> : <Sparkles className="h-3 w-3 text-amber-500" />}
                              Auto-Meta
                            </button>
                          </div>
                          {expandedMetaQuery === q.query && metaGenResults[q.query] && (
                            <div className="mx-2 mb-2 p-3 bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200/60 rounded-xl space-y-2 animate-in slide-in-from-top-1">
                              <div className="flex items-center gap-2 mb-1">
                                <Bot className="h-3.5 w-3.5 text-amber-600" />
                                <span className="text-[10px] font-bold text-amber-700 uppercase tracking-wider">AI-Generated Meta Tags</span>
                                <button onClick={() => setExpandedMetaQuery(null)} className="ml-auto p-0.5 rounded hover:bg-white/50">
                                  <ChevronUp className="h-3 w-3 text-gray-400" />
                                </button>
                              </div>
                              <div className="space-y-1.5">
                                <div className="flex items-start gap-2">
                                  <span className="text-[10px] font-semibold text-gray-500 uppercase w-12 flex-shrink-0 mt-0.5">Title</span>
                                  <p className="text-xs text-gray-800 flex-1">{metaGenResults[q.query].title}</p>
                                  <button onClick={() => copyToClipboard(metaGenResults[q.query].title, "Title")} className="p-1 rounded hover:bg-white/60 flex-shrink-0">
                                    {copiedText === metaGenResults[q.query].title ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-gray-400" />}
                                  </button>
                                </div>
                                <div className="flex items-start gap-2">
                                  <span className="text-[10px] font-semibold text-gray-500 uppercase w-12 flex-shrink-0 mt-0.5">Desc</span>
                                  <p className="text-xs text-gray-800 flex-1">{metaGenResults[q.query].description}</p>
                                  <button onClick={() => copyToClipboard(metaGenResults[q.query].description, "Description")} className="p-1 rounded hover:bg-white/60 flex-shrink-0">
                                    {copiedText === metaGenResults[q.query].description ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-gray-400" />}
                                  </button>
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </div>

              {/* ── AI SEO Strategist Panel ─────────────────────────────────── */}
              <div className="rounded-2xl border overflow-hidden" style={{ borderColor: 'rgba(3,114,255,0.2)' }}>
                <div className="p-5" style={{ background: 'linear-gradient(135deg, rgba(5,10,48,0.97) 0%, rgba(3,50,120,0.95) 100%)' }}>
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2.5">
                        <div className="p-2 rounded-xl" style={{ background: 'rgba(48,209,255,0.15)' }}>
                          <Bot className="h-5 w-5 text-cyan-400" />
                        </div>
                        <div>
                          <h3 className="text-sm font-bold text-white">AI SEO Strategist</h3>
                          <p className="text-[11px] text-slate-400">Analyzes your real search data to reveal opportunities</p>
                        </div>
                      </div>
                      <button
                        onClick={generateAIInsights}
                        disabled={aiInsightsLoading}
                      className={cn(
                        "flex items-center gap-2 text-xs font-semibold px-4 py-2 rounded-lg transition-all border",
                        aiInsights
                          ? "border-slate-500 text-slate-300 hover:bg-white/5"
                          : "text-white border-transparent hover:opacity-90"
                      )}
                      style={!aiInsights ? { background: 'linear-gradient(135deg, #0372ff, #30d1ff)' } : {}}
                    >
                      {aiInsightsLoading ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : aiInsights ? (
                        <RefreshCw className="h-3.5 w-3.5" />
                      ) : (
                        <Sparkles className="h-3.5 w-3.5" />
                      )}
                      {aiInsightsLoading ? 'Analyzing…' : aiInsights ? 'Regenerate' : 'Generate AI Insights'}
                    </button>
                  </div>

                  {/* Loading state */}
                  {aiInsightsLoading && (
                    <div className="flex items-center gap-3 mt-3">
                      {['Analyzing queries', 'Finding opportunities', 'Building strategy'].map((label, i) => (
                        <div key={label} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium border"
                          style={{ background: 'rgba(3,114,255,0.06)', borderColor: 'rgba(3,114,255,0.2)', color: '#30d1ff' }}>
                          <span className="relative flex h-1.5 w-1.5">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75"
                              style={{ background: '#30d1ff', animationDelay: `${i * 400}ms` }} />
                            <span className="relative inline-flex rounded-full h-1.5 w-1.5" style={{ background: '#0372ff' }} />
                          </span>
                          {label}
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Empty state */}
                  {!aiInsights && !aiInsightsLoading && (
                    <p className="text-xs text-slate-500 mt-2">
                      Click "Generate AI Insights" to get strategic, data-driven recommendations based on {enrichedQueries.length} queries, {quickWins.length} quick wins, and {ctrOpportunities.length} CTR opportunities.
                    </p>
                  )}
                </div>

                {/* AI Insights Results */}
                {aiInsights && aiInsights.length > 0 && (
                  <div className="bg-white p-5 space-y-3">
                    {aiInsights.map((insight, i) => {
                      const catConfig: Record<string, { color: string; bg: string; iconBg: string; Icon: React.ElementType }> = {
                        quick_wins: { color: 'text-emerald-700', bg: 'bg-emerald-50 border-emerald-200/60', iconBg: 'bg-emerald-100', Icon: Zap },
                        ctr_optimization: { color: 'text-amber-700', bg: 'bg-amber-50 border-amber-200/60', iconBg: 'bg-amber-100', Icon: Target },
                        declining_recovery: { color: 'text-rose-700', bg: 'bg-rose-50 border-rose-200/60', iconBg: 'bg-rose-100', Icon: TrendingDown },
                        growth_opportunity: { color: 'text-blue-700', bg: 'bg-blue-50 border-blue-200/60', iconBg: 'bg-blue-100', Icon: Lightbulb },
                      };
                      const conf = catConfig[insight.category] || catConfig.growth_opportunity;
                      return (
                        <div key={i} className={cn('rounded-xl border p-4', conf.bg)}>
                          <div className="flex items-start gap-3">
                            <div className={cn('p-2 rounded-lg flex-shrink-0 mt-0.5', conf.iconBg)}>
                              <conf.Icon className={cn('h-4 w-4', conf.color)} />
                            </div>
                            <div className="flex-1 min-w-0">
                              <p className={cn('text-xs font-bold mb-1', conf.color)}>{insight.icon} {insight.title}</p>
                              <p className="text-[11px] text-gray-600 leading-relaxed mb-2">{insight.body}</p>
                              {insight.actions && insight.actions.length > 0 && (
                                <div className="flex flex-wrap gap-1.5">
                                  {insight.actions.map((action, j) => (
                                    <span key={j} className="inline-flex items-center gap-1 text-[10px] font-medium px-2 py-1 rounded-md bg-white/70 border border-gray-200/60 text-gray-600">
                                      <ChevronRight className="h-2.5 w-2.5" />{action}
                                    </span>
                                  ))}
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                    <AIDisclaimer />
                  </div>
                )}
              </div>

              {/* ── Past AI Insights History ────────────────────────────────── */}
              {insightHistory.length > 0 && (
                <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm">
                  <button
                    onClick={() => setShowHistory(!showHistory)}
                    className="w-full flex items-center justify-between px-5 py-3 hover:bg-gray-50/50 transition-colors rounded-2xl"
                  >
                    <div className="flex items-center gap-2">
                      <History className="h-4 w-4 text-gray-400" />
                      <span className="text-sm font-semibold text-gray-700">Past AI Insights</span>
                      <span className="text-[10px] px-2 py-0.5 rounded-full bg-gray-100 text-gray-500 font-medium">{insightHistory.length}</span>
                    </div>
                    {showHistory ? <ChevronUp className="h-4 w-4 text-gray-400" /> : <ChevronDown className="h-4 w-4 text-gray-400" />}
                  </button>
                  {showHistory && (
                    <div className="px-5 pb-4 space-y-2 border-t border-gray-100 pt-3">
                      {insightHistory.map((item) => (
                        <div key={item.id} className="flex items-center gap-3 px-3 py-2.5 rounded-xl hover:bg-gray-50 border border-gray-100 cursor-pointer"
                          onClick={() => {
                            if (item.insight_type === 'strategist') {
                              setAiInsights(item.response as AIInsight[]);
                              toast.success("Loaded past insights");
                            } else if (item.insight_type === 'meta_description' && item.query_context) {
                              setMetaGenResults(prev => ({...prev, [item.query_context!]: item.response as MetaGenResult}));
                              setExpandedMetaQuery(item.query_context);
                              toast.success(`Loaded meta for "${item.query_context}"`);
                            } else if (item.insight_type === 'content_brief') {
                              setContentBrief(item.response as ContentBrief);
                              setActiveSection("queries");
                              toast.success("Loaded content brief");
                            }
                          }}
                        >
                          <div className={cn("p-1.5 rounded-lg",
                            item.insight_type === 'strategist' ? 'bg-blue-100' :
                            item.insight_type === 'meta_description' ? 'bg-amber-100' : 'bg-purple-100'
                          )}>
                            {item.insight_type === 'strategist' && <Bot className="h-3.5 w-3.5 text-blue-600" />}
                            {item.insight_type === 'meta_description' && <Sparkles className="h-3.5 w-3.5 text-amber-600" />}
                            {item.insight_type === 'content_brief' && <BookOpen className="h-3.5 w-3.5 text-purple-600" />}
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-xs font-semibold text-gray-700 truncate">
                              {item.insight_type === 'strategist' ? 'AI Strategy Analysis' :
                               item.insight_type === 'meta_description' ? `Meta: "${item.query_context}"` :
                               `Brief: "${item.query_context}"`}
                            </p>
                            <p className="text-[10px] text-gray-400 capitalize">{item.engine} · {item.date_range || 28}d range</p>
                          </div>
                          <div className="flex items-center gap-1 text-[10px] text-gray-400 flex-shrink-0">
                            <Clock className="h-3 w-3" />
                            {new Date(item.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* ─────────────────── QUERIES ─────────────────────────────────────── */}
          {activeSection === "queries" && (
            <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
              <SectionHeader
                title="All Search Queries"
                sub={`${filteredQueries.length} queries · last ${dateRange} days`}
              />
              <div className="flex items-center gap-3 mb-4 flex-wrap">
                <div className="relative flex-1 min-w-48">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-gray-400" />
                  <input type="text" placeholder="Filter queries…" value={querySearch}
                    onChange={e => setQuerySearch(e.target.value)}
                    className="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-300" />
                </div>
                <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
                  {(["all","brand","nonbrand"] as const).map(f => (
                    <button key={f} onClick={() => setQueryFilter(f)}
                      className={cn("px-3 py-1.5 rounded-lg text-xs font-semibold transition-all capitalize",
                        queryFilter === f ? "bg-white shadow-sm text-gray-800" : "text-gray-500 hover:text-gray-700")}>
                      {f === "nonbrand" ? "Non-Brand" : f === "all" ? "All" : "Brand"}
                    </button>
                  ))}
                </div>
              </div>
              <div className="grid grid-cols-[1fr_70px_80px_60px_60px_60px_85px] gap-2 px-2 pb-2 border-b border-gray-100">
                {["Query","Position","Impr.","Clicks","CTR","Trend",""].map(h => (
                  <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
                ))}
              </div>
              <div className="space-y-0.5 mt-1 max-h-[500px] overflow-y-auto">
                {filteredQueries.length === 0 ? (
                  <div className="text-center py-8 text-gray-400 text-sm">No queries found</div>
                ) : filteredQueries.map((q, i) => (
                  <div key={q.query} className="grid grid-cols-[1fr_70px_80px_60px_60px_60px_85px] gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50 group">
                    <span className="text-xs text-gray-700 truncate flex items-center gap-1.5">
                      <span className="text-[10px] text-gray-300 tabular-nums w-5 flex-shrink-0">{i + 1}</span>
                      {q.query}
                      {q.isBrand && <OpportunityBadge type="brand" />}
                    </span>
                    <span className="text-xs tabular-nums text-right font-medium text-gray-700">{fmtPos(q.position)}</span>
                    <span className="text-xs tabular-nums text-right text-gray-500">{fmt(q.impressions)}</span>
                    <span className="text-xs tabular-nums text-right font-semibold text-gray-900">{fmt(q.clicks)}</span>
                    <span className="text-xs tabular-nums text-right text-gray-500">{fmtCTR(q.ctr)}</span>
                    <span className="flex items-center justify-end">
                      {q.trend === "up" && <TrendingUp className="h-3.5 w-3.5 text-emerald-500" />}
                      {q.trend === "down" && <TrendingDown className="h-3.5 w-3.5 text-rose-500" />}
                      {q.trend === "stable" && <Minus className="h-3.5 w-3.5 text-gray-300" />}
                    </span>
                    <button
                      onClick={() => generateContentBriefForQuery(q.query, q.position, q.impressions)}
                      disabled={contentBriefLoading && contentBriefQuery === q.query}
                      className="px-2 flex items-center justify-center gap-1 text-[10px] font-semibold bg-blue-50 text-blue-600 border border-blue-200 rounded hover:bg-blue-100 transition-colors py-1"
                      title="Generate content brief"
                    >
                      {(contentBriefLoading && contentBriefQuery === q.query)
                        ? <Loader2 className="h-3 w-3 animate-spin text-blue-500" />
                        : <BookOpen className="h-3 w-3 text-blue-500" />}
                      Brief
                    </button>
                  </div>
                ))}
              </div>

              {/* Content Brief Panel */}
              {contentBrief && (
                <div className="mt-4 rounded-xl border overflow-hidden" style={{ borderColor: 'rgba(3,114,255,0.2)' }}>
                  <div className="px-4 py-3 flex items-center justify-between" style={{ background: 'linear-gradient(135deg, rgba(5,10,48,0.97) 0%, rgba(3,50,120,0.95) 100%)' }}>
                    <div className="flex items-center gap-2">
                      <BookOpen className="h-4 w-4 text-cyan-400" />
                      <span className="text-xs font-bold text-white">Content Brief: "{contentBrief.keyword}"</span>
                      <span className="text-[10px] px-2 py-0.5 rounded-full font-medium" style={{ background: 'rgba(48,209,255,0.15)', color: '#30d1ff' }}>
                        {contentBrief.intent}
                      </span>
                    </div>
                    <button onClick={() => setContentBrief(null)} className="p-1 rounded hover:bg-white/10">
                      <ChevronUp className="h-3.5 w-3.5 text-slate-400" />
                    </button>
                  </div>
                  <div className="bg-white p-4 space-y-3">
                    <div>
                      <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Suggested H1</p>
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-bold text-gray-900 flex-1">{contentBrief.suggestedTitle}</p>
                        <button onClick={() => copyToClipboard(contentBrief.suggestedTitle, "Title")} className="p-1 rounded hover:bg-gray-100 flex-shrink-0">
                          {copiedText === contentBrief.suggestedTitle ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-gray-400" />}
                        </button>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1.5">Suggested Headings</p>
                        <div className="space-y-1">
                          {contentBrief.headings.map((h, j) => (
                            <div key={j} className="flex items-center gap-1.5 text-xs text-gray-700">
                              <span className="text-[10px] font-bold text-blue-500">H2</span>
                              {h}
                            </div>
                          ))}
                        </div>
                      </div>
                      <div className="space-y-3">
                        <div>
                          <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Word Count</p>
                          <p className="text-xs font-medium text-gray-700">{contentBrief.wordCount}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Internal Links</p>
                          <div className="space-y-0.5">
                            {contentBrief.internalLinks.map((link, j) => (
                              <p key={j} className="text-xs text-blue-600">{link}</p>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>
                      <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Content Outline</p>
                      <p className="text-xs text-gray-600 leading-relaxed">{contentBrief.outline}</p>
                    </div>
                    <button
                      onClick={() => {
                        const text = `Content Brief: ${contentBrief.keyword}\n\nH1: ${contentBrief.suggestedTitle}\nIntent: ${contentBrief.intent}\nWord Count: ${contentBrief.wordCount}\n\nHeadings:\n${contentBrief.headings.map(h => `- ${h}`).join('\n')}\n\nInternal Links:\n${contentBrief.internalLinks.map(l => `- ${l}`).join('\n')}\n\nOutline:\n${contentBrief.outline}`;
                        copyToClipboard(text, "Full brief");
                      }}
                      className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 transition-all"
                    >
                      <Copy className="h-3 w-3" /> Copy Full Brief
                    </button>
                    <AIDisclaimer />
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ─────────────────── PAGES ───────────────────────────────────────── */}
          {activeSection === "pages" && (
            <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
              <SectionHeader
                title="Top Pages"
                sub={`${filteredPages.length} pages · last ${dateRange} days`}
              />
              <div className="relative mb-4">
                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-gray-400" />
                <input type="text" placeholder="Filter pages…" value={pageSearch}
                  onChange={e => setPageSearch(e.target.value)}
                  className="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-300" />
              </div>
              <div className="grid grid-cols-[1fr_80px_80px_60px] gap-2 px-2 pb-2 border-b border-gray-100">
                {["Page","Clicks","Impressions","CTR"].map(h => (
                  <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
                ))}
              </div>
              <div className="space-y-0.5 mt-1 max-h-[500px] overflow-y-auto">
                {filteredPages.length === 0 ? (
                  <div className="text-center py-8 text-gray-400 text-sm">No pages found</div>
                ) : filteredPages.map((p, i) => (
                  <div key={p.page} className="grid grid-cols-[1fr_80px_80px_60px] gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50">
                    <span className="text-xs text-gray-700 truncate flex items-center gap-1.5">
                      <span className="text-[10px] text-gray-300 tabular-nums w-5 flex-shrink-0">{i + 1}</span>
                      <FileText className="h-3 w-3 text-gray-300 flex-shrink-0" />
                      <a href={p.page} target="_blank" rel="noopener noreferrer"
                        className="truncate hover:text-blue-600 hover:underline" title={p.page}
                        onClick={e => e.stopPropagation()}>
                        {truncatePage(p.page)}
                      </a>
                    </span>
                    <span className="text-xs font-semibold text-gray-900 tabular-nums text-right">{fmt(p.clicks)}</span>
                    <span className="text-xs text-gray-500 tabular-nums text-right">{fmt(p.impressions)}</span>
                    <span className="text-xs text-gray-500 tabular-nums text-right">{fmtCTR(p.ctr)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ─────────────────── COUNTRIES ───────────────────────────────────── */}
          {activeSection === "countries" && (
            <div className="bg-white rounded-2xl border border-gray-200/80 shadow-sm p-5">
              <SectionHeader title="Traffic by Country" sub="Organic clicks and impressions by country" />
              {activeEngine !== "google" ? (
                <div className="text-center py-8 text-gray-400 text-sm">Country data is only available from Google Search Console.</div>
              ) : gscCountries.length === 0 ? (
                <div className="text-center py-8 text-gray-400 text-sm">No country data yet. Sync GSC to pull country breakdown.</div>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  <ResponsiveContainer width="100%" height={280}>
                    <BarChart data={gscCountries.slice(0, 12)} layout="vertical"
                      margin={{ top: 0, right: 12, bottom: 0, left: 60 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" horizontal={false} />
                      <XAxis type="number" tick={{ fontSize: 11, fill: "#9ca3af" }} axisLine={false} tickLine={false} />
                      <YAxis type="category" dataKey="country" tick={{ fontSize: 11, fill: "#6b7280" }}
                        axisLine={false} tickLine={false} width={56} tickFormatter={c => c.toUpperCase()} />
                      <RechartsTooltip
                        content={({ active, payload }) => {
                          if (!active || !payload?.length) return null;
                          const d = payload[0].payload;
                          return (
                            <div className="bg-white border border-gray-200 rounded-xl shadow-xl p-3 text-xs">
                              <p className="font-bold text-gray-800 mb-1">{d.country?.toUpperCase()}</p>
                              <p>Clicks: <strong>{d.clicks?.toLocaleString()}</strong></p>
                              <p>Impressions: <strong>{d.impressions?.toLocaleString()}</strong></p>
                            </div>
                          );
                        }}
                      />
                      <Bar dataKey="clicks" name="Clicks" radius={[0, 4, 4, 0]} fill="#3b82f6" />
                    </BarChart>
                  </ResponsiveContainer>

                  <div className="space-y-1">
                    <div className="grid grid-cols-[1fr_70px_90px] gap-2 px-2 pb-1 border-b border-gray-100">
                      {["Country","Clicks","Impressions"].map(h => (
                        <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
                      ))}
                    </div>
                    {gscCountries.map((c, i) => {
                      const maxClicks = gscCountries[0]?.clicks || 1;
                      const pct = (c.clicks / maxClicks) * 100;
                      return (
                        <div key={c.country} className="grid grid-cols-[1fr_70px_90px] gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50">
                          <span className="text-xs text-gray-700 flex items-center gap-2">
                            <span className="text-[10px] text-gray-300 w-4">{i + 1}</span>
                            <div className="flex-1 min-w-0">
                              <p className="font-medium">{c.country.toUpperCase()}</p>
                              <div className="h-1 bg-gray-100 rounded-full mt-0.5">
                                <div className="h-full bg-blue-400 rounded-full" style={{ width: `${pct}%` }} />
                              </div>
                            </div>
                          </span>
                          <span className="text-xs font-semibold text-gray-900 tabular-nums text-right">{fmt(c.clicks)}</span>
                          <span className="text-xs text-gray-500 tabular-nums text-right">{fmt(c.impressions)}</span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ─────────────────── TECHNICAL SEO ───────────────────────────────── */}
          {activeSection === "technical" && (
            <TechnicalSEO 
              clientId={clientId || ""} 
              siteUrl={gscIntegration?.site_url || bingIntegration?.site_url || null} 
            />
          )}

          {/* ─────────────────── COMPETITIVE INTEL ───────────────────────────── */}
          {activeSection === "competitive" && (
            <CompetitiveIntel 
              clientId={clientId || ""} 
              siteUrl={gscIntegration?.site_url || bingIntegration?.site_url || null} 
              competitors={competitors} 
            />
          )}

          {/* ─────────────────── CONTENT & ON-PAGE ───────────────────────────── */}
          {activeSection === "content" && (
            <ContentOnPage 
              clientId={clientId || ""} 
              siteUrl={gscIntegration?.site_url || bingIntegration?.site_url || null} 
              brandName={brandName} 
              gscData={gscData} 
              gscTopPages={gscTopPages} 
              dateRange={dateRange} 
            />
          )}

          {/* ─────────────────── BACKLINKS ───────────────────────────────────── */}
          {activeSection === "backlinks" && (
            <BacklinkModule 
              clientId={clientId || ""} 
              siteUrl={gscIntegration?.site_url || bingIntegration?.site_url || null} 
            />
          )}

          {/* ─────────────────── REPORTS & GOALS ─────────────────────────────── */}
          {activeSection === "reports" && (
            <ReportingGoals 
              clientId={clientId || ""} 
              siteUrl={gscIntegration?.site_url || bingIntegration?.site_url || null} 
              brandName={brandName} 
              metrics={gscMetrics} 
              topQueries={gscTopQueries} 
              gscData={gscData} 
              dateRange={dateRange} 
            />
          )}


          {/* ── No data state ─────────────────────────────────────────────────── */}
          {enrichedQueries.length === 0 && (
            <div className="bg-gray-50 rounded-2xl border border-dashed border-gray-200 p-8 text-center">
              <Globe className="h-8 w-8 text-gray-300 mx-auto mb-3" />
              <p className="text-sm font-semibold text-gray-500">No search data yet</p>
              <p className="text-xs text-gray-400 mt-1 mb-4">Sync your connected search platforms to pull data.</p>
              <div className="flex gap-2 justify-center">
                {gscConnected && (
                  <Button variant="outline" size="sm" onClick={syncGSC} disabled={syncing} className="gap-2 text-xs">
                    {syncing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
                    Sync GSC
                  </Button>
                )}
                {bingConnected && (
                  <Button variant="outline" size="sm" onClick={syncBing} disabled={syncing} className="gap-2 text-xs">
                    {syncing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
                    Sync Bing
                  </Button>
                )}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ── Shared table sub-components ────────────────────────────────────────────

function QueryTable({ rows, showTrend }: { rows: EnrichedQuery[]; showTrend?: boolean }) {
  if (rows.length === 0) return <div className="text-center py-6 text-gray-400 text-sm">No data</div>;
  return (
    <div className="space-y-0.5">
      <div className={cn("grid gap-2 px-2 pb-1.5 border-b border-gray-100",
        showTrend ? "grid-cols-[1fr_60px_60px_40px]" : "grid-cols-[1fr_60px_60px]")}>
        {["Query","Clicks","CTR", ...(showTrend ? ["↑↓"] : [])].map(h => (
          <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
        ))}
      </div>
      {rows.map((q, i) => (
        <div key={q.query} className={cn("grid gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50",
          showTrend ? "grid-cols-[1fr_60px_60px_40px]" : "grid-cols-[1fr_60px_60px]")}>
          <span className="text-xs text-gray-700 truncate flex items-center gap-1">
            <span className="text-[10px] text-gray-300 w-4">{i + 1}</span>
            {q.query}
            {q.isBrand && <span className="text-[10px] text-blue-500">●</span>}
          </span>
          <span className="text-xs font-semibold text-gray-900 tabular-nums text-right">{fmt(q.clicks)}</span>
          <span className="text-xs text-gray-500 tabular-nums text-right">{fmtCTR(q.ctr)}</span>
          {showTrend && (
            <span className="flex items-center justify-end">
              {q.trend === "up" && <TrendingUp className="h-3 w-3 text-emerald-500" />}
              {q.trend === "down" && <TrendingDown className="h-3 w-3 text-rose-500" />}
              {q.trend === "stable" && <Minus className="h-3 w-3 text-gray-300" />}
            </span>
          )}
        </div>
      ))}
    </div>
  );
}

function PageTable({ rows }: { rows: PageRow[] }) {
  if (rows.length === 0) return <div className="text-center py-6 text-gray-400 text-sm">No data</div>;
  return (
    <div className="space-y-0.5">
      <div className="grid grid-cols-[1fr_60px_60px] gap-2 px-2 pb-1.5 border-b border-gray-100">
        {["Page","Clicks","CTR"].map(h => (
          <span key={h} className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider text-right first:text-left">{h}</span>
        ))}
      </div>
      {rows.map((p, i) => (
        <div key={p.page} className="grid grid-cols-[1fr_60px_60px] gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50">
          <span className="text-xs text-gray-700 truncate flex items-center gap-1">
            <span className="text-[10px] text-gray-300 w-4">{i + 1}</span>
            <a href={p.page} target="_blank" rel="noopener noreferrer"
              className="truncate hover:text-blue-600" title={p.page} onClick={e => e.stopPropagation()}>
              {truncatePage(p.page, 40)}
            </a>
          </span>
          <span className="text-xs font-semibold text-gray-900 tabular-nums text-right">{fmt(p.clicks)}</span>
          <span className="text-xs text-gray-500 tabular-nums text-right">{fmtCTR(p.ctr)}</span>
        </div>
      ))}
    </div>
  );
}

function RecoCard({ icon: Icon, color, title, body }: {
  icon: React.ElementType; color: string; title: string; body: string;
}) {
  const colorMap: Record<string, string> = {
    emerald: "bg-emerald-50 border-emerald-200/60 text-emerald-600",
    amber: "bg-amber-50 border-amber-200/60 text-amber-600",
    rose: "bg-rose-50 border-rose-200/60 text-rose-600",
    blue: "bg-blue-50 border-blue-200/60 text-blue-600",
    purple: "bg-purple-50 border-purple-200/60 text-purple-600",
  };
  const iconColorMap: Record<string, string> = {
    emerald: "bg-emerald-100", amber: "bg-amber-100", rose: "bg-rose-100",
    blue: "bg-blue-100", purple: "bg-purple-100",
  };
  return (
    <div className={cn("flex items-start gap-3 rounded-xl border p-3.5", colorMap[color])}>
      <div className={cn("p-2 rounded-lg flex-shrink-0 mt-0.5", iconColorMap[color])}>
        <Icon className="h-4 w-4" />
      </div>
      <div>
        <p className="text-xs font-bold mb-0.5">{title}</p>
        <p className="text-[11px] opacity-80 leading-relaxed">{body}</p>
      </div>
    </div>
  );
}
